### ISSUE TITLE
I message u on https://github.com/udacimak/udacimak/issues/59

### ISSUE THREAD

**Issue by rupeshvins** [vsay01/Summary_Note_Udacity_Deep_learning_PyTorch#1]
Hi
I make message on https://github.com/udacimak/udacimak/issues/59 for Udacity Deep Learning with Pytorch, I install Docker toolbox and github for download but at my end both r not working. https://classroom.udacity.com/courses/ud188, can u plz download and share via google drive. thanks

**Comment by vsay01** [comment]
@rupeshvins I reached out to Udacity lead about sharing the offline content, and she doesn't recommend for us to do that. She encourage us to download from the resources in the classroom.
Feel free to post any issues you have while using the tool so that the community can help.
I tried to find your name in slack for easier communication, but I can't find you. feel free to DM me on slack if you have any questions / concerns.
